// ============================================================================
// Voice Clone API Route — CosyVoice2 Local Zero-Shot Cloning
// Replaces Fish Audio cloud cloning with local CosyVoice2 inference.
//
// CosyVoice2 cloning pipeline:
//   Reference audio (10-30s) → speaker embedding → any text synthesised
//   in that voice identity via inference_zero_shot().
//
// POST body: multipart/form-data
//   audio         : File  (WAV/MP3/WebM/M4A)
//   voiceName     : string
//   voiceDescription : string (optional)
//   category      : string
//   languageCode  : string  (e.g. "vi-VN")
//   transcript    : string  (optional — improves quality significantly)
// ============================================================================

import { NextRequest, NextResponse } from 'next/server';
import { appendFileSync } from 'fs';

const COSYVOICE_URL = process.env.COSYVOICE_URL ?? process.env.KOKORO_URL ?? 'http://localhost:8080';
const CLONE_ENDPOINT = `${COSYVOICE_URL}/tts/clone`;

export async function POST(request: NextRequest) {
  try {
    const incomingForm = await request.formData();

    const voiceName     = incomingForm.get('voiceName')     as string ?? '';
    const voiceDesc     = incomingForm.get('voiceDescription') as string ?? '';
    const category      = incomingForm.get('category')      as string ?? 'general';
    const languageCode  = incomingForm.get('languageCode')  as string ?? 'vi-VN';
    const transcript    = incomingForm.get('transcript')    as string ?? '';
    const audioFile     = incomingForm.get('audio')         as File | null;

    if (!audioFile || !voiceName.trim()) {
      return NextResponse.json(
        { success: false, error: 'Thiếu file âm thanh hoặc tên giọng nói.', timestamp: new Date().toISOString() },
        { status: 400 }
      );
    }

    // ── Forward to local CosyVoice2 service ────────────────────────────────
    const proxyForm = new FormData();
    proxyForm.append('audio',         audioFile, audioFile.name || 'voice_sample.wav');
    proxyForm.append('voice_name',    voiceName);
    proxyForm.append('language_code', languageCode);
    proxyForm.append('transcript',    transcript);
    // voice_id auto-generated by the service

    let serviceRes: Response;
    try {
      serviceRes = await fetch(CLONE_ENDPOINT, {
        method: 'POST',
        body: proxyForm,
        signal: AbortSignal.timeout(120_000),  // cloning can take ~30-60s
      });
    } catch (fetchErr) {
      const msg = fetchErr instanceof Error ? fetchErr.message : String(fetchErr);
      console.error('[Clone] Cannot reach CosyVoice2 service:', msg);
      return NextResponse.json(
        {
          success: false,
          error: `Không kết nối được CosyVoice2 service (${COSYVOICE_URL}). Chạy start_tts.sh trong WSL2.`,
          timestamp: new Date().toISOString(),
        },
        { status: 503 }
      );
    }

    if (!serviceRes.ok) {
      const errorText = await serviceRes.text();
      console.error('[Clone] CosyVoice2 error:', serviceRes.status, errorText.slice(0, 200));
      try { appendFileSync('clone-error.log', `[${new Date().toISOString()}] ${serviceRes.status}: ${errorText}\n`); } catch {}
      return NextResponse.json(
        {
          success: false,
          error: `Lỗi từ CosyVoice2: ${serviceRes.status} — ${errorText.slice(0, 100)}`,
          timestamp: new Date().toISOString(),
        },
        { status: 502 }
      );
    }

    const data = await serviceRes.json() as {
      success: boolean; voice_id: string; voice_name: string;
      engine: string; language?: string; message?: string;
    };

    if (!data.success || !data.voice_id) {
      return NextResponse.json(
        { success: false, error: 'CosyVoice2 không trả về voice_id.', timestamp: new Date().toISOString() },
        { status: 502 }
      );
    }

    // ── Build Voice object for the frontend catalog ───────────────────────
    const gradients: [string, string][] = [
      ['#f97316', '#ea580c'], ['#8b5cf6', '#7c3aed'],
      ['#ec4899', '#f43f5e'], ['#10b981', '#059669'],
      ['#3b82f6', '#1d4ed8'], ['#f43f5e', '#e11d48'],
    ];
    const gradient = gradients[Math.floor(Math.random() * gradients.length)];

    const newVoice = {
      id:          data.voice_id,
      name:        voiceName,
      label:       `${voiceName} — Nhân bản (CosyVoice2)`,
      countryCode: languageCode.includes('-') ? languageCode.split('-')[1] : 'VN',
      languageCode,
      category,
      gender:      'neutral' as const,
      description: voiceDesc || `Giọng nhân bản CosyVoice2: ${voiceName}`,
      avatarColors: gradient,
      engine:      'cosyvoice2' as const,
      geminiVoiceName: data.voice_id,  // CosyVoice2 voice ID = file stem
      isCustom:    true,
      createdAt:   new Date().toISOString(),
    };

    console.log(`[Clone] ✓ voice_id=${data.voice_id} name=${voiceName} lang=${languageCode}`);

    return NextResponse.json({
      success: true,
      voice: newVoice,
      timestamp: new Date().toISOString(),
      message: `Giọng "${voiceName}" đã được nhân bản thành công bằng CosyVoice2!`,
    });

  } catch (error) {
    console.error('[Clone] Unexpected error:', error);
    return NextResponse.json(
      {
        success: false,
        error: 'Lỗi server khi xử lý voice cloning.',
        timestamp: new Date().toISOString(),
      },
      { status: 500 }
    );
  }
}
