// ============================================================================
// Multi-Country Voice Catalog
// Layer 1 — Static voice data for the platform
// ============================================================================

import { Voice, Country } from '@/types/voice.types';

/** Supported countries with their language codes */
export const COUNTRIES: Country[] = [
  { code: 'VN', name: 'Việt Nam', flag: '🇻🇳', languageCode: 'vi-VN', languageName: 'Tiếng Việt' },
  { code: 'US', name: 'Hoa Kỳ', flag: '🇺🇸', languageCode: 'en-US', languageName: 'English' },
  { code: 'ES', name: 'Tây Ban Nha', flag: '🇪🇸', languageCode: 'es-ES', languageName: 'Español' },
  { code: 'RU', name: 'Nga', flag: '🇷🇺', languageCode: 'ru-RU', languageName: 'Русский' },
  { code: 'JP', name: 'Nhật Bản', flag: '🇯🇵', languageCode: 'ja-JP', languageName: '日本語' },
  { code: 'KR', name: 'Hàn Quốc', flag: '🇰🇷', languageCode: 'ko-KR', languageName: '한국어' },
  { code: 'FR', name: 'Pháp', flag: '🇫🇷', languageCode: 'fr-FR', languageName: 'Français' },
  { code: 'CN', name: 'Trung Quốc', flag: '🇨🇳', languageCode: 'zh-CN', languageName: '中文' },
  { code: 'DE', name: 'Đức', flag: '🇩🇪', languageCode: 'de-DE', languageName: 'Deutsch' },
  { code: 'TH', name: 'Thái Lan', flag: '🇹🇭', languageCode: 'th-TH', languageName: 'ภาษาไทย' },
];

/** Pre-built voice catalog */
export const VOICE_CATALOG: Voice[] = [
  // ── Vietnamese Voices (Mapped strictly to Gemini 5 voices) ────────
  {
    id: 'vi-aoede',
    name: 'Mai',
    label: 'Mai - Nhẹ nhàng',
    countryCode: 'VN',
    languageCode: 'vi-VN',
    category: 'narration',
    gender: 'female',
    description: 'Giọng nữ êm ái, nhẹ nhàng (Gemini Aoede)',
    avatarColors: ['#14b8a6', '#0d9488'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'vi-kore',
    name: 'Linh',
    label: 'Linh - Trong trẻo',
    countryCode: 'VN',
    languageCode: 'vi-VN',
    category: 'conversational',
    gender: 'female',
    description: 'Giọng nữ rõ ràng, trong trẻo (Gemini Kore)',
    avatarColors: ['#ec4899', '#f43f5e'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'vi-charon',
    name: 'Đức',
    label: 'Đức - Trầm ấm',
    countryCode: 'VN',
    languageCode: 'vi-VN',
    category: 'general',
    gender: 'male',
    description: 'Giọng nam trầm ấm, đáng tin cậy (Gemini Charon)',
    avatarColors: ['#10b981', '#059669'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'vi-fenrir',
    name: 'Phong',
    label: 'Phong - Mạnh mẽ',
    countryCode: 'VN',
    languageCode: 'vi-VN',
    category: 'news',
    gender: 'male',
    description: 'Giọng nam dứt khoát, mạnh mẽ (Gemini Fenrir)',
    avatarColors: ['#f97316', '#ea580c'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'vi-puck',
    name: 'Minh',
    label: 'Minh - Sôi động',
    countryCode: 'VN',
    languageCode: 'vi-VN',
    category: 'conversational',
    gender: 'male',
    description: 'Giọng nam trẻ trung, năng động (Gemini Puck)',
    avatarColors: ['#3b82f6', '#1d4ed8'],
    isCustom: false,
    createdAt: '2025-01-01',
  },

  // ── English (US) Voices ────────────────────────────────
  {
    id: 'en-james',
    name: 'James',
    label: 'James - Narrator',
    countryCode: 'US',
    languageCode: 'en-US',
    category: 'narration',
    gender: 'male',
    description: 'Deep, cinematic narrator voice for documentaries',
    avatarColors: ['#6366f1', '#4f46e5'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'en-sarah',
    name: 'Sarah',
    label: 'Sarah - Conversational',
    countryCode: 'US',
    languageCode: 'en-US',
    category: 'conversational',
    gender: 'female',
    description: 'Friendly, natural conversational voice for vlogs',
    avatarColors: ['#f472b6', '#ec4899'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'en-michael',
    name: 'Michael',
    label: 'Michael - News',
    countryCode: 'US',
    languageCode: 'en-US',
    category: 'news',
    gender: 'male',
    description: 'Professional news anchor voice with clear enunciation',
    avatarColors: ['#0ea5e9', '#0284c7'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'en-emma',
    name: 'Emma',
    label: 'Emma - Young',
    countryCode: 'US',
    languageCode: 'en-US',
    category: 'conversational',
    gender: 'female',
    description: 'Young, energetic voice for social media content',
    avatarColors: ['#a78bfa', '#8b5cf6'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'en-david',
    name: 'David',
    label: 'David - Commercial',
    countryCode: 'US',
    languageCode: 'en-US',
    category: 'general',
    gender: 'male',
    description: 'Authoritative commercial voiceover for advertisements',
    avatarColors: ['#f59e0b', '#d97706'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'en-olivia',
    name: 'Olivia',
    label: 'Olivia - Meditation',
    countryCode: 'US',
    languageCode: 'en-US',
    category: 'narration',
    gender: 'female',
    description: 'Calm, soothing voice for meditation and ASMR',
    avatarColors: ['#34d399', '#10b981'],
    isCustom: false,
    createdAt: '2025-01-01',
  },

  // ── Spanish Voices ─────────────────────────────────────
  {
    id: 'es-animals',
    name: 'Animals TBN',
    label: 'Animals TBN - Chung',
    countryCode: 'ES',
    languageCode: 'es-ES',
    category: 'general',
    gender: 'male',
    description: 'Narración general en español con tono natural',
    avatarColors: ['#f97316', '#dc2626'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'es-tbn-dl',
    name: 'TBN DL',
    label: 'TBN DL - Hội thoại',
    countryCode: 'ES',
    languageCode: 'es-ES',
    category: 'conversational',
    gender: 'male',
    description: 'Voz conversacional para diálogos y entrevistas',
    avatarColors: ['#6366f1', '#3b82f6'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'es-carmen',
    name: 'Carmen',
    label: 'Carmen - Noticias',
    countryCode: 'ES',
    languageCode: 'es-ES',
    category: 'news',
    gender: 'female',
    description: 'Voz profesional para noticias y reportajes',
    avatarColors: ['#ec4899', '#be185d'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'es-pablo',
    name: 'Pablo',
    label: 'Pablo - Publicidad',
    countryCode: 'ES',
    languageCode: 'es-ES',
    category: 'general',
    gender: 'male',
    description: 'Voz enérgica para contenido publicitario',
    avatarColors: ['#10b981', '#047857'],
    isCustom: false,
    createdAt: '2025-01-01',
  },

  // ── Russian Voices ─────────────────────────────────────
  {
    id: 'ru-khao',
    name: 'Khảo cổ Nga',
    label: 'Khảo cổ Nga - Chung',
    countryCode: 'RU',
    languageCode: 'ru-RU',
    category: 'general',
    gender: 'male',
    description: 'Общий русский голос для повествования',
    avatarColors: ['#ef4444', '#b91c1c'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'ru-natasha',
    name: 'Natasha',
    label: 'Natasha - Диалог',
    countryCode: 'RU',
    languageCode: 'ru-RU',
    category: 'conversational',
    gender: 'female',
    description: 'Естественный женский голос для диалогов',
    avatarColors: ['#a78bfa', '#7c3aed'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'ru-dmitri',
    name: 'Dmitri',
    label: 'Dmitri - Новости',
    countryCode: 'RU',
    languageCode: 'ru-RU',
    category: 'news',
    gender: 'male',
    description: 'Профессиональный голос для новостей',
    avatarColors: ['#0ea5e9', '#0369a1'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'ru-anna',
    name: 'Anna',
    label: 'Anna - Аудиокниги',
    countryCode: 'RU',
    languageCode: 'ru-RU',
    category: 'narration',
    gender: 'female',
    description: 'Тёплый голос для аудиокниг и медитации',
    avatarColors: ['#f472b6', '#db2777'],
    isCustom: false,
    createdAt: '2025-01-01',
  },

  // ── Japanese Voices ────────────────────────────────────
  {
    id: 'ja-yuki',
    name: 'Yuki',
    label: 'Yuki - ナレーション',
    countryCode: 'JP',
    languageCode: 'ja-JP',
    category: 'narration',
    gender: 'female',
    description: '落ち着いたナレーション向きの女性ボイス',
    avatarColors: ['#f43f5e', '#e11d48'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'ja-takeshi',
    name: 'Takeshi',
    label: 'Takeshi - ニュース',
    countryCode: 'JP',
    languageCode: 'ja-JP',
    category: 'news',
    gender: 'male',
    description: 'プロフェッショナルなニュースキャスターの声',
    avatarColors: ['#3b82f6', '#2563eb'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'ja-sakura',
    name: 'Sakura',
    label: 'Sakura - 会話',
    countryCode: 'JP',
    languageCode: 'ja-JP',
    category: 'conversational',
    gender: 'female',
    description: '明るく親しみやすいカジュアルボイス',
    avatarColors: ['#ec4899', '#f472b6'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'ja-kenji',
    name: 'Kenji',
    label: 'Kenji - 広告',
    countryCode: 'JP',
    languageCode: 'ja-JP',
    category: 'general',
    gender: 'male',
    description: 'エネルギッシュな広告ナレーション',
    avatarColors: ['#f59e0b', '#d97706'],
    isCustom: false,
    createdAt: '2025-01-01',
  },

  // ── Korean Voices ──────────────────────────────────────
  {
    id: 'ko-soyeon',
    name: 'Soyeon',
    label: 'Soyeon - 나레이션',
    countryCode: 'KR',
    languageCode: 'ko-KR',
    category: 'narration',
    gender: 'female',
    description: '부드럽고 전문적인 내레이션 음성',
    avatarColors: ['#8b5cf6', '#6d28d9'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'ko-junhyeok',
    name: 'Junhyeok',
    label: 'Junhyeok - 뉴스',
    countryCode: 'KR',
    languageCode: 'ko-KR',
    category: 'news',
    gender: 'male',
    description: '명확하고 신뢰감 있는 뉴스 앵커 음성',
    avatarColors: ['#0ea5e9', '#0284c7'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'ko-minji',
    name: 'Minji',
    label: 'Minji - 대화',
    countryCode: 'KR',
    languageCode: 'ko-KR',
    category: 'conversational',
    gender: 'female',
    description: '밝고 친근한 대화체 음성',
    avatarColors: ['#f43f5e', '#e11d48'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'ko-hyunwoo',
    name: 'Hyunwoo',
    label: 'Hyunwoo - 광고',
    countryCode: 'KR',
    languageCode: 'ko-KR',
    category: 'general',
    gender: 'male',
    description: '힘있고 에너지 넘치는 광고 음성',
    avatarColors: ['#10b981', '#059669'],
    isCustom: false,
    createdAt: '2025-01-01',
  },

  // ── French Voices ──────────────────────────────────────
  {
    id: 'fr-jacques',
    name: 'Jacques',
    label: 'Jacques - Narration',
    countryCode: 'FR',
    languageCode: 'fr-FR',
    category: 'narration',
    gender: 'male',
    description: 'Voix masculine profonde pour la narration cinématographique',
    avatarColors: ['#1d4ed8', '#3b82f6'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'fr-chloe',
    name: 'Chloé',
    label: 'Chloé - Conversation',
    countryCode: 'FR',
    languageCode: 'fr-FR',
    category: 'conversational',
    gender: 'female',
    description: 'Voix féminine naturelle pour les vlogs et podcasts',
    avatarColors: ['#f472b6', '#ec4899'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'fr-philippe',
    name: 'Philippe',
    label: 'Philippe - Actualités',
    countryCode: 'FR',
    languageCode: 'fr-FR',
    category: 'news',
    gender: 'male',
    description: 'Voix de journaliste professionnel pour les actualités',
    avatarColors: ['#0ea5e9', '#0369a1'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'fr-amelie',
    name: 'Amélie',
    label: 'Amélie - Publicité',
    countryCode: 'FR',
    languageCode: 'fr-FR',
    category: 'general',
    gender: 'female',
    description: 'Voix dynamique et séduisante pour la publicité',
    avatarColors: ['#a78bfa', '#8b5cf6'],
    isCustom: false,
    createdAt: '2025-01-01',
  },

  // ── Science (US) ───────────────────────────────────────
  {
    id: 'en-science',
    name: 'Khoa Học Mỹ',
    label: 'Khoa Học Mỹ - Chung',
    countryCode: 'US',
    languageCode: 'en-US',
    category: 'general',
    gender: 'male',
    description: 'Educational science narrator with clear articulation',
    avatarColors: ['#22c55e', '#16a34a'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'es-science',
    name: 'Khoa Học TBN',
    label: 'Khoa Học Tây Ban Nha - Chung',
    countryCode: 'ES',
    languageCode: 'es-ES',
    category: 'general',
    gender: 'female',
    description: 'Voz educativa para contenido científico',
    avatarColors: ['#f97316', '#ea580c'],
    isCustom: false,
    createdAt: '2025-01-01',
  },
];

/**
 * Get voices filtered by country code
 */
export function getVoicesByCountry(countryCode: string): Voice[] {
  return VOICE_CATALOG.filter(v => v.countryCode === countryCode);
}

/**
 * Get voices filtered by category
 */
export function getVoicesByCategory(category: string): Voice[] {
  return VOICE_CATALOG.filter(v => v.category === category);
}

/**
 * Find a voice by its ID
 */
export function findVoiceById(id: string): Voice | undefined {
  return VOICE_CATALOG.find(v => v.id === id);
}
